# Generated by Django 5.2.2 on 2026-02-04 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Signup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('f_name', models.CharField(max_length=100)),
                ('gender', models.CharField()),
                ('contactno', models.BigIntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('address', models.CharField(max_length=1000)),
                ('state', models.CharField()),
                ('district', models.CharField()),
                ('city', models.CharField()),
                ('password', models.CharField(max_length=100)),
            ],
        ),
    ]
